import React from 'react';
import { Category, PriceType, ArtistStatus, Show } from './types';

export const VIBE_OPTIONS = [
  'Elegant / Premium',
  'Energetisch / Party',
  'Spektakulär / Wow-Effekt',
  'Interaktiv',
  'Hintergrund / Ambient',
  'Humorvoll'
];

export const MOCK_SHOWS: Show[] = [
  {
    id: '1',
    shortId: '7f3a2c',
    slug: 'elegantes-streichquartett',
    artistId: 'a1',
    artistName: 'Berlin String Ensemble',
    title: 'Elegantes Streichquartett für Galas',
    category: Category.CLASSICAL,
    instrumentationText: '2 Violinen, Viola, Cello',
    extractedTags: ['Streichquartett', 'Klassik', 'Hochzeit'],
    vibeTags: ['Elegant / Premium', 'Hintergrund / Ambient'],
    shortDescriptionFacts: 'Professionelles Quartett mit Repertoire von Bach bis Bridgerton.',
    salesPitchText: 'Verleihen Sie Ihrem Event eine zeitlose Eleganz mit unseren harmonischen Klängen.',
    durationMinutes: 90,
    languageOptions: ['DE', 'EN'],
    priceType: PriceType.RANGE,
    priceMin: 1200,
    priceMax: 2500,
    photoUrls: ['https://picsum.photos/seed/strings/800/600'],
    videoUrls: ['https://www.youtube.com/watch?v=dQw4w9WgXcQ'],
    status: ArtistStatus.PUBLISHED,
  },
  {
    id: '2',
    shortId: '9b2d1e',
    slug: 'jazz-trio-berlin',
    artistId: 'a2',
    artistName: 'The Blue Note Trio',
    title: 'Smooth Jazz Trio',
    category: Category.BAND,
    instrumentationText: 'Piano, Kontrabass, Schlagzeug',
    extractedTags: ['Jazz', 'Piano', 'Dinner Musik'],
    vibeTags: ['Hintergrund / Ambient', 'Elegant / Premium'],
    shortDescriptionFacts: 'Klassischer Trio-Sound für Empfänge und Networking-Events.',
    salesPitchText: 'Dezente Untermalung für anspruchsvolle Gespräche und entspannte Atmosphäre.',
    durationMinutes: 120,
    languageOptions: ['DE', 'EN'],
    priceType: PriceType.POA,
    photoUrls: ['https://picsum.photos/seed/jazz/800/600'],
    videoUrls: ['https://www.youtube.com/watch?v=dQw4w9WgXcQ'],
    status: ArtistStatus.PUBLISHED,
  },
  {
    id: '3',
    shortId: '4c8e7f',
    slug: 'aerial-silk-show',
    artistId: 'a3',
    artistName: 'Aero Dynamics',
    title: 'Vertikaltuch Akrobatik',
    category: Category.ACROBATICS,
    extractedTags: ['Akrobatik', 'Zirkus', 'Show-Act'],
    vibeTags: ['Spektakulär / Wow-Effekt'],
    shortDescriptionFacts: 'Atemberaubende Luftakrobatik in 6-10 Metern Höhe.',
    salesPitchText: 'Ein Moment des Staunens, wenn die Schwerkraft scheinbar aufgehoben wird.',
    durationMinutes: 15,
    languageOptions: ['EN'],
    priceType: PriceType.RANGE,
    priceMin: 800,
    priceMax: 1500,
    photoUrls: ['https://picsum.photos/seed/aerial/800/600'],
    videoUrls: ['https://www.youtube.com/watch?v=dQw4w9WgXcQ'],
    status: ArtistStatus.PUBLISHED,
  },
  {
    id: '4',
    shortId: '1a2b3c',
    slug: 'contemporary-dance-duo',
    artistId: 'a4',
    artistName: 'Duo Motion',
    title: 'Modern Dance Performance',
    category: Category.DANCE,
    extractedTags: ['Tanz', 'Modern', 'Performance Art'],
    vibeTags: ['Elegant / Premium', 'Interaktiv'],
    shortDescriptionFacts: 'Emotionale Tanzdarbietung mit Fokus auf Storytelling.',
    salesPitchText: 'Körperbeherrschung trifft auf tiefe Emotionen in einer fesselnden Choreografie.',
    durationMinutes: 20,
    languageOptions: ['DE', 'EN'],
    priceType: PriceType.RANGE,
    priceMin: 600,
    priceMax: 1200,
    photoUrls: ['https://picsum.photos/seed/dance/800/600'],
    videoUrls: ['https://www.youtube.com/watch?v=dQw4w9WgXcQ'],
    status: ArtistStatus.PUBLISHED,
  },
];
